### ISSUE TITLE
Could not inject dependency via guice

### ISSUE THREAD

**Issue by pavlokuziak** [modernmt/modernmt-java#1]
I try to inject dependency in guice project, but I get error: `java.lang.ClassNotFoundException: com.auth0.jwt.interfaces.JWTVerifier`. Could you help with that? Thanks in advance!

**Comment by davc0n** [comment]
Don't know guice, could you share a minimal sample application in order to replicate the issue?
I'll take a look and see if can help

**Comment by pavlokuziak** [comment]
I'll try and get back to you later this week or early next week
